## Exercise

Write a program to implement perceptron for random 10 fruits having 3 attributes *shape*, *texture* and *weight*.
Their values are integer and may range between -1 and 1.

## Solution:

In [1]:
import numpy as np

#### Generating random dataset

In [2]:
X = np.random.randint(-1, 1, size = (10, 3))
print(X)

[[-1 -1  0]
 [-1 -1  0]
 [-1 -1 -1]
 [-1 -1  0]
 [ 0  0 -1]
 [ 0 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [ 0  0 -1]]


In [3]:
wt = np.random.randint(-1, 1, size = (1, 3))
bias = 0
print(wt)

[[-1  0  0]]


In [4]:
target = np.array([1, 1, 1, 1, 1, -1, -1, -1, -1, -1])
print(target)

[ 1  1  1  1  1 -1 -1 -1 -1 -1]


Let's convert each array elements into separate array

In [5]:
target = np.expand_dims(target, axis = 1)
print(target)

[[ 1]
 [ 1]
 [ 1]
 [ 1]
 [ 1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]


In [6]:
net_input = np.dot(X, wt.T) + bias
print(net_input)

[[1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]]


What is difference between **np.reshape()** and **np.resize()**? <br>
 **Ans**: reshape() is more strict tahn resize()

### Firing perceptron

In [8]:
def ppn(x):
    threshold = 0
    out = []
    for i in x:
        if i > threshold:
            out.append('Apple')
        else:
            out.append('Orange')
    return out

In [10]:
ppn(net_input)

['Apple',
 'Apple',
 'Apple',
 'Apple',
 'Orange',
 'Orange',
 'Apple',
 'Apple',
 'Apple',
 'Orange']